version: '3'
services:  
    backend:   
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - ./backend:/app 
        ports:
            - "5000:5000"   
        restart: always    

    frontend:
        ports:
            - "3000:3000"   
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - ./frontend:/app    
        #request will forward to same url, so we only need /api to distinguish that this request will forward to our backend           
        environment: 
            - REACT_APP_BACKEND_URL=/api
            - CHOKIDAR_USEPOLLING=true
    
    # nginx:
    #     build:
    #         context: ./nginx
    #         dockerfile: Dockerfile.dev
    #     ports: 
    #         - 3000:80
    #     restart: always

volumes: 
    db-volume: