version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./backend:/app
        environment:
            - CURRENT_ENV=deployment
        restart: always            
        ports:
            - 5000:5000

    frontend:
        mem_limit: "1300M"
        stdin_open: true
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./frontend:/app
        restart: always
        environment:
            - REACT_APP_BACKEND_URL=/api
            - REACT_APP_CURRENT_ENV=deployment
            - REACT_APP_API_URL=http://localhost:5000/v1/api/accounts/checkCaptcha
            - REACT_APP_RECAPTCHA_SITE_KEY=6LfWAsciAAAAAERYL1EmEuEuB-_HUcOITh0ZUGNC
        ports:
            - 3000:3000

volumes:
    db-volume:
