version: '3.8'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./backend:/app
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CURRENT_ENV=testing
        restart: always
        ports:
            - 5000:5000

    frontend:
        mem_limit: "1300M"
        stdin_open: true
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./frontend:/app
        restart: always
        environment:            
            - REACT_APP_BACKEND_URL=/api
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_CURRENT_ENV=testing
        ports:
            - 3000:3000
volumes:
    db-volume:
