version: '3'
services:  
    backend:   
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - ./backend:/app 
        ports:
            - "5000:5000"   
        restart: always
        environment:
            - CURRENT_ENV=deployment    

    frontend:
        ports:
            - "3000:3000"   
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - ./frontend:/app    
        
        environment: 
            - REACT_APP_BACKEND_URL=/api
            - CHOKIDAR_USEPOLLING=true
volumes: 
    db-volume: