@startuml
@startmindmap
+ learn4fund
++_ .gitignore
++_ docker-compose.dev.yml
++_ docker-compose.yml
++_ README.md
++ backend
+++_ .env
+++_ Dockerfile
+++_ Dockerfile.dev
+++_ package-lock.json
+++_ package.json
+++_ server.js
+++ api
++++_ accounts.route.js
++++_ admin.route.js
++++_ carts.route.js
++++_ companies.route.js
++++_ courses.route.js
++++_ donations.route.js
++++_ images.route.js
++++_ payments.route.js
++++_ reviews.route.js
+++ config
++++_ db.js
+++ controller
++++_ accounts.controller.js
++++_ admin.controller.js
++++_ carts.controller.js
++++_ companies.controller.js
++++_ courses.controller.js
++++_ donations.controller.js
++++_ payments.controller.js
++++_ reviews.controller.js
+++ dao
++++_ coursesDAO.js
+++ middleware
++++_ authMiddleware.js
++++_ errorMiddleware.js   
+++ models
++++_ accountModel.js
++++_ billAddressModel.js
++++_ cartModel.js
++++_ companyModel.js
++++_ courseModel.js
++++_ creditCardModel.js
++++_ donationModel.js
++++_ logsModel.js
++++_ payMethodModel.js
++++_ reviewModel.js
++++_ transactionModel.js
++++_ voucherModel.js
++ frontend
+++_ .gitignore
+++_ Dockerfile
+++_ Dockerfile.dev
+++_ package-lock.json
+++_ package.json
+++_ postcss.config.js
+++_ README.md
+++_ tailwind.config.js
+++_ yarn.lock
+++ nginx
++++_ default.conf
+++ public
++++_ favicon.ico
++++_ index.html
++++_ logo192.png
++++_ logo512.png
++++_ manifest.json
++++_ robots.txt
+++ src
++++_ App.jsx
++++_ http-common.js
++++_ index.js
++++_ logo.svg
++++_ tailwind.css
++++ app
+++++_ store.js
++++ assets
+++++ datasets
++++++_ courses.json
++++++_ dataset.js     
+++++ images
++++++_ background.jpg
++++++_ business partners.png
++++++_ default_person.jpg
++++++_ donation banner.png
++++++_ donation drive.png
++++++_ download.jpeg
++++++_ top donators.png
+++++ vectors
++++++_ mastercard.png
++++++_ networking.png
++++++_ noimage.png
++++++_ singaporeflag.png
++++++_ visa.png
++++ components
+++++ admin
++++++_ AddCourseModal.jsx
++++++_ BannedUsers.jsx
++++++_ CoursesCatalog.jsx
++++++_ SuspiciousActivities.jsx
++++++_ SuspiciousActivity.js
++++++_ SuspiciousActivityList.js
++++++_ UserManagementActivity.js
++++++_ UserManagementActivityList.js
+++++ banner
++++++_ Banner.jsx
++++++_ Subscribe.jsx
+++++ catalog
++++++_ CourseInfo.jsx
+++++ footer
++++++_ Footer.jsx
+++++ nav
++++++_ Nav.jsx
+++++ profile
++++++_ Account.jsx
++++++_ ChangePassword.jsx
++++++_ Profile.jsx
++++++_ TransactionHistory.jsx
++++ features
+++++ user
++++++_ userActions.js
++++++_ userSlice.js
++++ hooks
+++++_ useAuth.jsx
+++++_ useNav.jsx
++++ modals
+++++_ ConfirmationModal.jsx
+++++_ CreditCardModal.jsx
+++++_ NewsLetterModal.jsx
+++++_ OTPModal.jsx
+++++_ PromotionModal.jsx
++++ policies
+++++_ Cookie.jsx
+++++_ Privacy.jsx
+++++_ Toc.jsx
++++ routes
+++++_ Admin.jsx
+++++_ Cart.jsx
+++++_ Catalog.jsx
+++++_ Donations.jsx
+++++_ Homepage.jsx
+++++_ Login.jsx
+++++_ Login2FA.jsx
+++++_ ProtectedRoute.jsx
+++++_ Settings.jsx
+++++_ Signup.jsx
++++ services
+++++_ accounts.js
+++++_ admin.js
+++++_ carts.js
+++++_ courses.js
+++++_ donations.js
+++++_ images.js
+++++_ payment.js
+++++_ reviews.js
++ nginx
+++_ default.dev.conf
+++_ Dockerfile.dev
+++_ ssl.conf

@endmindmap
