FROM node:latest

# WORKDIR '/app'

COPY package.json package-lock.json ./

RUN npm install

COPY . .

#CMD ["npm", "run", "start", "--node-flags", "--max-old-space-size=512"]
CMD ["npm", "run", "dev"]
